Migrate to GitHub Actions
wpilibsuite/GradleRIO pull request #438
Opened 2020-10-11 10:56 UTC by Starlight220

Resolves #435 

@AustinShalit I'm not sure I used correct equivalents of the Azure Tasks (`Gradle`, `CopyFiles`, and `PublishBuildArtifacts`). Any chance you can take a look?

2020-10-11 12:06 UTC, AustinShalit requested changes

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +
```suggestion
    - uses: actions/checkout@v2
       with:
         fetch-depth: 0
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ./gradlew -Xmx3072m build publishToMavenLocal PatchExamples --stacktrace -PlocalPublish
```suggestion
      run: ./gradlew build publishToMavenLocal PatchExamples --stacktrace -PlocalPublish
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ./gradlew build
```suggestion
      run: ./gradlew build
      working-directory: examples/cpp
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ./gradlew build
```suggestion
      run: ./gradlew build
      working-directory: examples/java
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ./gradlew build
```suggestion
      run: ./gradlew build
      working-directory: examples/jni
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ./gradlew build
```suggestion
      run: ./gradlew build
      working-directory: examples/kotlin
```

2020-10-11 12:06 UTC, AustinShalit commented on .github/workflows/ci.yml
> +          name: "Examples"
```suggestion
    - uses: actions/upload-artifact@v2
      with:
        name: Examples
        path: build/distributions
```

2020-10-11 12:07 UTC, AustinShalit commented
Thank you @Starlight220 I've left some comments just to make the file more succinct.

2020-10-11 13:40 UTC, AustinShalit commented on .github/workflows/ci.yml
> +
```suggestion
```

2020-10-11 13:40 UTC, AustinShalit commented on .github/workflows/ci.yml
> +
```suggestion
```

2020-10-11 16:17 UTC, AustinShalit commented on .github/workflows/ci.yml
> +         fetch-depth: 0
I think the spacing is wrong here but can't fix it in the GH editor.

2020-10-11 16:18 UTC, AustinShalit commented
Please also update the README badge and delete the azure and travis files.

2020-10-11 17:34 UTC, Starlight220 commented
Nope. Why isn't it running?

2020-10-11 17:53 UTC, Starlight220 commented
Is there a reason it would fail because of missing permissions only on the JNI build and not on the Cpp and Java ones? 
Kotlin etc doesn't get tested because of the JNI failure.

2020-10-15 21:47 UTC, AustinShalit requested changes

2020-10-15 21:47 UTC, AustinShalit commented on .github/workflows/ci.yml
> +#     container: wpilib/roborio-cross-ubuntu:2020-18.04
```suggestion
```

2020-10-15 21:47 UTC, AustinShalit commented on .github/workflows/ci.yml
> +        ls -al ~/.m2
```suggestion
```

2020-10-15 21:47 UTC, AustinShalit commented on .github/workflows/ci.yml
> +#     container: wpilib/roborio-cross-ubuntu:2020-18.04
```suggestion
```

2020-10-16 13:15 UTC, AustinShalit requested changes
Sorry @Starlight220 just a few more things.

2020-10-16 13:15 UTC, AustinShalit commented on .github/workflows/ci.yml
> +    - uses: actions/download-artifact@v2.0.5
```suggestion
    - uses: actions/download-artifact@v2
```

2020-10-16 13:15 UTC, AustinShalit commented on .github/workflows/ci.yml
> +    - uses: actions/upload-artifact@v2.2.0
```suggestion
    - uses: actions/upload-artifact@v2
```

2020-10-16 13:15 UTC, AustinShalit commented on README.md
> +![CI](https://github.com/wpilibsuite/GradleRIO/workflows/CI/badge.svg)
```suggestion
![CI](https://github.com/wpilibsuite/GradleRIO/workflows/CI/badge.svg)

```

2020-10-16 14:48 UTC, AustinShalit approved these changes

2020-10-24 21:24 UTC, merged