Add new image versions
wpilibsuite/GradleRIO pull request #458
Opened 2020-11-16 14:54 UTC by Starlight220

Resolves #457

2020-11-16 14:55 UTC, AustinShalit commented
This is going to need a little bit more work because we need to update the logic too.

2020-11-16 14:55 UTC, Starlight220 commented on src/main/groovy/edu/wpi/first/gradlerio/wpi/WPIExtension.groovy
> +    static final String[] validImageVersions = ['2020_v10', '2021_v1', '2021_v2', '2021_v3.*']
Not sure that this is the right way to add the wildcard.

2020-11-16 14:57 UTC, Starlight220 commented
What logic is needed that isn't currently implemented?
Other than the wildcard, that is.

2020-11-16 15:00 UTC, AustinShalit commented
See here: https://github.com/wpilibsuite/GradleRIO/blob/210522e03dff78b19e66971ebfe1eeb1d695c2e9/src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy#L83-L114

2020-11-16 15:03 UTC, Starlight220 commented
Yeah, I know that that's where the logic will need to be changed. My question was as to what logic do we want to add. Is the wildcard support the only feature we want to add?

2020-11-16 16:50 UTC, AustinShalit commented
oh... yea I think so.

2020-11-16 17:00 UTC, Starlight220 commented
Ok, I found a regex that also matches versions like `YEAR_vX.Y` as well as the old `YEAR_vX` versions. Now I'm working on comparing the strings unless someone has an idea for that already.

2020-11-17 04:58 UTC, PeterJohnson requested changes

2020-11-17 04:58 UTC, PeterJohnson commented on src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy
> +                "roborio-${team}-FRC.frc-field.local".toString()        // Practice Field mDNS
This reformatting is unrelated to the rest of the change.

2020-11-17 04:58 UTC, PeterJohnson commented on src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy
> +        final Pattern pattern = Pattern.compile("^IMAGEVERSION\\s=\\s\\\"FRC_roboRIO_(\\d{4}_v\\d(?:\\.\\d+)?)\\\"")
The second `\\d` needs a `+` after it to handle versions like `2020.10`

2020-11-18 04:52 UTC, PeterJohnson commented on src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy
> +            } else {
this needs an `else if (index > image.size()) { return false }` otherwise the substring fails

2020-11-18 05:11 UTC, closed without merging