Update to gradle 7.3
wpilibsuite/GradleRIO pull request #570
Opened 2021-12-10 01:49 UTC by ThadHouse

2021-12-11 18:54 UTC, sciencewhiz commented
Should we use 7.3.1 instead?

2021-12-11 18:58 UTC, ThadHouse commented
Ah I didn't see that. Yes we should

2021-12-19 02:52 UTC, sciencewhiz requested changes
7,3,2 is out

2021-12-19 06:40 UTC, ThadHouse commented
Bumped to 7.3.2

2021-12-19 07:04 UTC, merged